
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 09 21:15:42 EST 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbol {
  /* terminals */
  public static final int TIMES = 4;
  public static final int READ = 13;
  public static final int ELSE = 14;
  public static final int PLUS = 2;
  public static final int RPAREN = 7;
  public static final int NOTEQUAL = 23;
  public static final int SEMI = 20;
  public static final int QUOTES = 10;
  public static final int END = 17;
  public static final int RETURN = 15;
  public static final int ASIGN = 22;
  public static final int IF = 8;
  public static final int LPAREN = 6;
  public static final int WRITE = 12;
  public static final int ID = 9;
  public static final int BEGIN = 16;
  public static final int TYPE = 19;
  public static final int COMMA = 11;
  public static final int NUMBER = 24;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int MAIN = 18;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int EQ = 21;
}

